build:
  maxIssues: 0

complexity:
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    ignoreAnnotatedFunctions:
      - 'Preview'
      - 'Composable'
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 150
    ignoreAnnotated:
      - 'Composable'

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignoreRanges: true
    ignoreLocalVariableDeclaration: true
    ignoreAnnotated:
      - 'Composable'
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
    excludePackageStatements: true
    excludeImportStatements: true
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
  MatchingDeclarationName:
    active: false

exceptions:
  TooGenericExceptionCaught:
    allowedExceptionNameRegex: '_|(ignore|expected|e|ex)'
  SwallowedException:
    allowedExceptionNameRegex: '_|(ignore|expected|e|ex)'

performance:
  SpreadOperator:
    active: false
